### ISSUE TITLE
hey，bro  从您博客找过来的。想问能分享一下训练好的燕姿模型吗？纯个人想试着玩一玩，但是pc没有显卡用来训练，且实在没找到您邮箱，只能在这提issue问一下，冒昧打扰啦

### ISSUE THREAD

**Issue by ZunxiaoXu** [CheneyDev/Prompt-Store#1]

**Comment by CheneyDev** [comment]
链接：[https://drive.google.com/file/d/1hrAkr0UA4vvefRseGkyvoEQIpkn9LSx-/view?usp=sharing](https://drive.google.com/file/d/1hrAkr0UA4vvefRseGkyvoEQIpkn9LSx-/view?usp=sharing)
请尽快下载，链接会在三天后失效🤓

**Comment by ZunxiaoXu** [comment]
感谢佬，虽然合成痕迹明显，已成功复现：）

**Comment by CheneyDev** [comment]
不客气 : )
